name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: "1.x"

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Get PR Number
        id: get-pr
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed" \
            | jq --arg SHA "$GITHUB_SHA" '.[] | select(.merge_commit_sha == $SHA) | .number')
          echo "PR Number: $PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"
          echo "ARTIFACT_NAME=artifact-PR${PR_NUMBER}" >> $GITHUB_ENV

      - name: Download from S3
        run: |
          aws s3 cp s3://lambda-change-tracker/${{ env.ARTIFACT_NAME }}.txt ./

      - name: Read updated Lambda list
        run: |
          readarray -t lambda_functions < ./${{ env.ARTIFACT_NAME }}.txt
          for lambda in "${lambda_functions[@]}"
          do
            echo "$lambda"
          done

      - name: Build and Zip Files
        run: |
          readarray -t lambda_functions < ./${{ env.ARTIFACT_NAME }}.txt
          for lambda in "${lambda_functions[@]}"
          do
            if [ -f lambdas/$lambda/package.json ]; then # Check if Nodejs project
              echo "Node.js project detected: $lambda"
              cd "${GITHUB_WORKSPACE}/lambdas/${lambda}"
              npm install
              # If you have a build script defined in package.json
              npm run build --if-present
              # If you have a test script defined in package.json
              npm run test --if-present
              zip -r $lambda.zip .
              cd -
            else
              echo "Building and zipping $lambda"
              cd "${GITHUB_WORKSPACE}/lambdas/${lambda}"
              GOOS=linux GOARCH=amd64 go build -o bootstrap
              zip $lambda.zip bootstrap
              cd -
            fi
          done

      - name: Deploy Lambda function(s)
        run: |
          readarray -t lambda_functions < ./${{ env.ARTIFACT_NAME }}.txt
          for lambda in "${lambda_functions[@]}"
          do
            echo "$lambda"
          done
          for lambda in "${lambda_functions[@]}"
          do
            echo "Deploying $lambda"
            aws lambda update-function-code --function-name $lambda --zip-file fileb://lambdas/$lambda/$lambda.zip
          done
